version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    environment:
      LOG4J_ROOTLOGGER: ERROR, stdout
    ports:
      - "2181:2181" 
  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        w3g-router-loopback:1:1:delete --config=compression.type=snappy
        id-bulk-stats-requests:1:1:delete --config=compression.type=snappy
        id-bulk-stats-responses:1:1:delete --config=compression.type=snappy
        id-stats-updates:1:1:delete --config=compression.type=snappy
        id-lobby-requests:1:1:delete --config=compression.type=snappy
        id-replays-responses:1:1:delete --config=compression.type=snappy
      LOG4J_ROOTLOGGER: ERROR, stdout
    ports:
      - "9092:9092" 
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /tmp/db
      MONGO_LOG_DIR: /dev/null
    volumes:
        - /tmp/db:/data/db
    ports:
        - "27017:27017" 