version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    environment:
      LOG4J_ROOTLOGGER: ERROR, stdout
    networks:
      - w3g
  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        w3g-router-loopback:1:1:delete --config=compression.type=snappy
        id-bulk-stats-requests:1:1:delete --config=compression.type=snappy
        id-bulk-stats-responses:1:1:delete --config=compression.type=snappy
        id-stats-updates:1:1:delete --config=compression.type=snappy
        id-lobby-requests:1:1:delete --config=compression.type=snappy
        id-replays-responses:1:1:delete --config=compression.type=snappy
      LOG4J_ROOTLOGGER: ERROR, stdout
    networks:
      - w3g
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
        - /tmp/db:/data/db
    networks:
      - w3g
  w3g-router-ms:
    image: lesuorac/w3g-all
    command: "/app/target/release/w3g-router-ms"
    restart: always
    depends_on:
      - kafka
    environment:
      ROCKET_ENV: production
      #RUST_LOG: error
      RUST_LOG: w3g_common=error,w3g_router_ms=debug
      KAFKA_URIS: kafka:9092
    ports:
      - "8080:80" 
    networks:
      - w3g
  w3g-stats-ms:
    image: lesuorac/w3g-all
    command: "/app/target/release/w3g-stats-ms"
    restart: always
    depends_on:
      - kafka
      - mongodb  
    environment: 
      #RUST_LOG: error
      RUST_LOG: w3g_common=error,w3g_stats_ms=debug
      KAFKA_URIS: kafka:9092
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: islandDefense
      MONGO_COLLECTION: playerStats
    networks:
      - w3g
  w3g-lobby-ms:
    image: lesuorac/w3g-all
    command: "/app/target/release/w3g-lobby-ms"
    restart: always
    depends_on:
      - kafka  
    environment: 
      #RUST_LOG: error
      RUST_LOG: w3g_common=error,w3g_lobby_ms=debug
      KAFKA_URIS: kafka:9092
    networks:
      - w3g
  w3g-downloader-ms:
    image: lesuorac/w3g-all
    command: "/app/target/release/w3g-downloader-ms"
    restart: always
    depends_on:
      - kafka
      - mongodb  
    environment: 
      #RUST_LOG: error
      RUST_LOG: w3g_common=error,w3g_downloader_ms=trace
      KAFKA_URIS: kafka:9092
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: islandDefense
      MONGO_COLLECTION: replays
     # REPLAY_PATH: /data/replays
    volumes:
        - /tmp/replays:/data/replays
    networks:
      - w3g
  w3g-rating-ms:
    image: lesuorac/w3g-all
    command: "/app/target/release/w3g-rating-ms"
    restart: always
    depends_on:
      - kafka
      - w3g-downloader-ms
    environment: 
      #RUST_LOG: error
      RUST_LOG: w3g_common=error,w3g_rating_ms=info
      KAFKA_URIS: kafka:9092
    networks:
      - w3g

networks:
  w3g:
    driver: bridge